version: '3'

services:
  db:
    image: postgres:15
    restart: always
    container_name: phoenix-chat
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: phoenix_chat_dev
    ports:
      - "7432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: { }
